#%RAML 1.0 DataType
type: object
minProperties: 1
maxProperties: 2
additionalProperties: false
properties:
  id:
    type: number
    required: true
    example: 1
  name:
    type: string
    required: true
    example: "Bat"
